### ISSUE TITLE
addBatch INSERT not using the column order if specified in the INSERT statement

### ISSUE THREAD

**Issue by dwayneberry** [omnisci/mapd-core#124]
see

https://community.mapd.com/t/mapd-java-jdbc-preparedstatement-bug/693/2

When we fix this we should also convert the api call over to use `load_table_binary_columnar`

**Comment by randyzwitch** [comment]
@niviksha It would be great if we could prioritize a fix for this, as it has downstream impacts with other data ingestion tools (Streamsets specifically in my case). When loading data in batch, JDBC doesn't respect the column order, instead alphabetizing the columns. This is a pretty odd limitation, and one that's hard to understand from an end user's perspective.

**Comment by randyzwitch** [comment]
Fixed by #335
