### ISSUE TITLE
output_columnar option hint and columnar representation of results

### ISSUE THREAD

**Issue by isolenta** [omnisci/mapd-core#130]
I'm trying to enable output_columnar_hint in ExecutionOptions and run query picked from one of ExecuteTest's cases: 
> SELECT dd AS key1, COUNT(*) AS value1 FROM test GROUP BY key1 HAVING key1 IS NOT NULL ORDER BY key1, value1 DESC LIMIT 12

I got assertion: 

> F1108 06:26:04.447276 12206 GroupByAndAggregate.cpp:2879] Check failed: !outputColumnar()

For most other test queries I tried there was still rowwise data layout in ResultSet storage buffers and only small subset of queries enables columnar approach (canOutputColumnar() is true). By the way complex queries with few execution steps have expensive data conversion from rowwise to columnar representation.

What a reason to don't support columnar format everywhere, and is it justified to implement such support?

**Comment by randyzwitch** [comment]
Closing this issue, as I believe the codebase has moved on sufficiently where this is no longer an issue and columnar results are available for most if not all queries. If this continues to be an issue, please let us know.
