### ISSUE TITLE
compiler mapd-core error

### ISSUE THREAD

**Issue by xuxilei** [omnisci/mapd-core#17]
[root@localhost ~]# cd mapd-core-master/

[root@localhost mapd-core-master]# cd build/

[root@localhost build]# cmake -DCMAKE_BUILD_TYPE=debug -DMAPD_IMMERSE_DOWNLOAD=off ..

CMake Error at /usr/local/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):

  Could NOT find Thrift (missing: Thrift_LIBRARY Thrift_VERSION)

Call Stack (most recent call first):

  /usr/local/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)

  cmake/Modules/FindThrift.cmake:92 (find_package_handle_standard_args)

  CMakeLists.txt:84 (find_package)

 

 

-- Configuring incomplete, errors occurred!

See also "/root/mapd-core-master/build/CMakeFiles/CMakeOutput.log".

See also "/root/mapd-core-master/build/CMakeFiles/CMakeError.log".

[root@localhost build]#

**Comment by xuxilei** [comment]
is the script wrong?

**Comment by xuxilei** [comment]
is another centos still installed ?

**Comment by dwayneberry** [comment]
Hi

It cannot find your Thrift libraries.

It appears you have another issue here https://github.com/mapd/mapd-core/issues/16  regarding downloading the dependencies I think these to issues are related #16

**Comment by xuxilei** [comment]
"it cannot find your Thrift libraries."
Thrift libraries are:
[root@localhost lib]# ls

libthrift_c_glib.a  libthrift_c_glib.la  libthrift_c_glib.so  libthrift_c_glib.so.0  libthrift_c_glib.so.0.0.0  pkgconfig

[root@localhost lib]# cd pkgconfig/

[root@localhost pkgconfig]# ls

thrift_c_glib.pc

[root@localhost pkgconfig]#

**Comment by xuxilei** [comment]
SOS

**Comment by dwayneberry** [comment]
How did you get your mapd-deps?

Did you build them or download them.

It appears your paths are not set up correctly.

Are you following the instructions here: 
https://github.com/mapd/mapd-core#building
and here:
https://github.com/mapd/mapd-core#dependencies

**Comment by randyzwitch** [comment]
Closing, as the codebase has changed so much since the ticket was open that whatever the issue might have been is likely drifted. In general, using either Ubuntu 18.04LTS or Centos 7 and installing using the provided dependency scripts or the Docker containers provided by OmniSci is recommended.
