### ISSUE TITLE
JDBC support for public Date getDate(int columnIndex, Calendar cal) throws SQLException

### ISSUE THREAD

**Issue by ssainz** [omnisci/mapd-core#204]
JDBC support for:

java.sql.ResultSet: public Date getDate(int columnIndex, Calendar cal) throws SQLException
java.sql.ResultSet: public Date getTime(int columnIndex, Calendar cal) throws SQLException

**Comment by ssainz** [comment]
Also timestamp: 

public Timestamp getTimestamp(int columnIndex, Calendar cal) throws SQLException 

BTW, the return of getTime should be Time, not Date

**Comment by dwayneberry** [comment]
Thanks,

The error it throws Identifies these methods as "Not supported yet"

We are slowly working through all methods, as internal priorities allow, but welcome contributions from the broader community if you need these fixed sooner.

**Comment by cdessanti** [comment]
I implement d those methods last December to make the driver work with microstrategy; but I don’t know if I implemented them correctly. It worked but I haven’t control on ms calls so I am not sure the result is correct.
I can share the code anyway

Ottieni Outlook per iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ssainz** [comment]
@cdessanti  thanks , awesome!  I wonder whether we can push them to main/next branch? In that way everyone takes advantage of it.

**Comment by randyzwitch** [comment]
Fixed by #331
