### ISSUE TITLE
Updates to mapd-deps-ubuntu.sh 

### ISSUE THREAD

**Issue by pearu** [omnisci/mapd-core#213]
To successfully run scripts/mapd-deps-ubuntu.sh  in a newly created Docker container (Ubuntu 16.04), the following commands were required prior running the script:
```apt-get install sudo cppcheck clang-tidy libegl1-mesa-dev```

**Comment by wangliangxu** [comment]
Confirm this issue.

**Comment by randyzwitch** [comment]
Closing this issue, as the fix is generally to use Ubuntu 18.04LTS to install the newer/proper library versions or to use the Docker containers pushed by OmniSci.
