### ISSUE TITLE
CMake minimal version is inadequate

### ISSUE THREAD

**Issue by pearu** [omnisci/mapd-core#262]
According to CMakeLists.txt the minimum required version is 2.8 while subsequently VERSION_GREATER_EQUAL boolean operator is used that was introduced in CMake release 3.7 (https://cmake.org/cmake/help/v3.7/release/3.7.html).

Ubuntu 16.04 provides CMake version 3.5.1.

Options:
1. Require cmake 3.7 as the minimal requirement.
2. Find a workaround to the usage of VERSION_GREATER_EQUAL without changing cmake 2.8 requirement condition.
3. Anything else?

**Comment by randyzwitch** [comment]
Thanks for reporting this. @andrewseidl , since you were the last one to touch CMakeLists.txt, do you have a feeling about bumping the minimum requirement for Cmake? 

I can confirm that MapD-Core won't build on Ubuntu 16.04 using CMake 3.5.1 from a clean Docker image, so something needs to change.
