### ISSUE TITLE
JDBC driver has a wrong value in META-INF/services/java.sql.Driver

### ISSUE THREAD

**Issue by cdessanti** [omnisci/mapd-core#267]
The jar containing the mapd JDBC driver has a wrong value in META-INF/services/java.sql.Driver leading to the exception "java.sql.SQLException: No suitable driver found" on third-party products that rely upon that value to register the class of the driver.

The actual value for the file is org.postgresql.Driver

**Comment by dwayneberry** [comment]
@cdessanti I think you may be looking at or using an older driver.  Please confirm you are looking at the new jdbc driver labelled something like

```mapdjdbc-4.x.x-SNAPSHT.jar```

**Comment by cdessanti** [comment]
The older drivers labeled mapdjdbc-1.0 were fine; I noticed this problem when I tried to modify the driver compiling a recent snapshot of mapd-core.
After that, I checked the jdbc driver on 4.1, and 4.1.1 release of mapd-ce and both of them have the Postgres class.


Ottieni Outlook per Android<https://aka.ms/ghei36>



Da: Michael Thomson
Inviato: mercoledì 19 settembre, 00:41
Oggetto: Re: [mapd/mapd-core] JDBC driver has a wrong value in META-INF/services/java.sql.Driver (#267)
A: mapd/mapd-core
Cc: Candido Dessanti, Mention


@<https://github.com/cdessanti>cdessanti<https://github.com/cdessanti> I think you may be looking at or using an older driver. Please confirm you are looking at the new JDBC driver labeled something like
mapdjdbc-4.x.x-SNAPSHT.jar

**Comment by randyzwitch** [comment]
Marking this resolved. The original postgres reference is incorrect and corrected.
