### ISSUE TITLE
Port 9093 error during startup

### ISSUE THREAD

**Issue by Jiede1** [omnisci/mapd-core#270]
In the process of starting the mapd server, the error that the port 9093 cannot be opened is reported, but the SQL statement can be executed normally..it is confusing
```
[root@cdsw3 build]# ./bin/mapd_server
Thrift: Mon Oct  8 20:15:01 2018 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
Thrift: Mon Oct  8 20:15:01 2018 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
Thrift: Mon Oct  8 20:15:01 2018 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
Thrift: Mon Oct  8 20:15:01 2018 TSocket::open() connect() <Host: localhost Port: 9093>Connection refused
```

**Comment by senatorgrant** [comment]
@Jiede1 thanks for noticing this. We're aware of it and we're working on a fix to error handling so that it's less confusing.

**Comment by AilsaGUAN** [comment]
> @Jiede1 thanks for noticing this. We're aware of it and we're working on a fix to error handling so that it's less confusing.

Hi, may i konw is this error fixed?

**Comment by randyzwitch** [comment]
@AilsaGUAN 

This isn't an error, but a warning at start up that can be ignored. However, because it is confusing, we will be working on a fix.
