### ISSUE TITLE
JDBC setBoolean implementation

### ISSUE THREAD

**Issue by pedorich-n** [omnisci/mapd-core#274]
Hi there! 
Why does the implementation of `setBoolean` in JDBC drive converts values to `t` or `f`? I get an exception `java.sql.SQLException: Query failed : Exception: Cannot compare between BOOLEAN and VARCHAR`. 

I'm using `mapdjdbc-1.0-SNAPSHOT-jar-with-dependencies.jar` and as I see, implementation is the same in master branch, https://github.com/omnisci/mapd-core/blob/master/java/mapdjdbc/src/main/java/com/mapd/jdbc/MapDPreparedStatement.java#L167 

Example code:
```scala
  val sql  = s"select 1 from example where hasException = ?"
  val stmt = ConnectionPool.get().borrow().prepareStatement(sql)
  stmt.setBoolean(1, false)
  val resultSet = stmt.executeQuery()
  println(resultSet.getInt(1))
```
```bash
22:22:24.092 [run-main-6] DEBUG com.mapd.jdbc.MapDStatement - sql is :'select 1 from example where hasException = 'f' LIMIT 100000'
22:22:24.092 [run-main-6] DEBUG com.mapd.jdbc.MapDStatement - afterFnSQL is :'select 1 from example where hasException = 'f' LIMIT 100000'
```

I obtain connection via ScalikeJDBC's `ConnectionPool`, but it's the same as `DriverManager.getConnection(...)`

```scala
  Class.forName("com.mapd.jdbc.MapDDriver")
  ConnectionPool.singleton("jdbc:mapd:192.168.1.9:9091:db_test", "mapd", "HyperInteractive")
```

Am I doing something wrong?

**Comment by andrewseidl** [comment]
Thanks for the report. I've pushed a potential fix here: https://github.com/omnisci/mapd-core/pull/276 , should be merged in a day or so.

I've opened #277 requesting adding how to build the JDBC driver on its own. It's possible, but it's currently intertwined with the rest of our CMake-based build. It's basically two `thrift -gen java` runs to generate the bindings, then need to remember to set a few properties when running maven.
