### ISSUE TITLE
MAPD [SQL insert multiple rows in one query]

### ISSUE THREAD

**Issue by MadDoxXimba** [omnisci/mapd-core#288]
Hello,

currently i'm facing a problem where i'd like to insert multiple rows in a table by using one sql query:
ex: insert into table values (v1, v2), (v3, v4), ....

I tried to search in the documentation for the right syntax but in vain...
may i get some help please ?

Thanks in advance

**Comment by VrajPandya** [comment]
We follow a very simple insert syntax to inset data in which is 

INSERT INTO <table> VALUES(v1, v2, v3, v4, ...); So I would not use multiple parenthesis.

You can find the documentation for insert here: 

https://www.omnisci.com/docs/latest/5_dml.html#insert

But I would encourage you to use `copy from` command which does bulk inserts and much faster than doing individual inserts. 

https://www.omnisci.com/docs/latest/6_loading_data.html#copy-from

**Comment by MadDoxXimba** [comment]
Hi thank you for your quick answer.
My use case is to use the jdbc mapd (or equivalent ) to insert data in a table in batch mode on a server side java app.
I don't think the copy from would be of use to me since it takes a file located on the filesystem as parameter ? => maybe i'm mistaken...

**Comment by randyzwitch** [comment]
Hi @MadDoxXimba - 

One other thing you can do instead of single record insertion is to use `prepareStatement` and `addBatch` to load the data in batches via JDBC. One thing to keep in mind is that currently our JDBC driver has a small issue (tracked [here](https://github.com/omnisci/mapd-core/issues/124)) that the table definition has to be in alphabetical order. But inserting data in this manner will lead to a significant performance improvement.

**Comment by MadDoxXimba** [comment]
@randyzwitch 

Thanks for suggesstion. But to my knowledge, prepareStatement support only data types of the language i'm using (Java: int, String, etc...) with the classic sql datatypes. How about geospatial data types? for instance Point or Geometry, can i still use prepareStatement ? if so i would be grateful if you can show me an example on how it's done :+1:

**Comment by randyzwitch** [comment]
To be honest, I'm not a Java programmer, so I don't know the specifics of this question in regards to geospatial types. 

You're probably better served by moving this discussion to the [community forum](https://community.omnisci.com/) where more users (including OmniSci employees) will be able to provide suggestions for your specific use case.
