### ISSUE TITLE
Thrift Error!

### ISSUE THREAD

**Issue by ggcking** [omnisci/mapd-core#296]
hi, I'm trying to use mapd CE GPU on CentOS7.  When I $MAPD_PATH/bin/initdb -f $MAPD_STORAGE, it is show Thrift: Mon Dec 10 22:13:39 2018 TSocket::open() connect() <Host: localhost Port: 39093>Connection refused.  
I use mapdql , it can create a table t1, but select * from t1, it show Thrift error: No more data to read.
What is the problem, How to solve it ! thank i

**Comment by ggcking** [comment]
Maybe cuda driver error ? I set the mapd.conf, let it run as CPU, it is ok .
But I want to test is as GPU, but how ?
I run systemctl status mapd_server: it shows 

12月 11 01:11:18 madpsvr mapd_server[5104]: 0(261) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(270) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(275) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(157) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(160) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(163) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(189) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(190) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(197) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
12月 11 01:11:18 madpsvr mapd_server[5104]: 0(198) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression

**Comment by randyzwitch** [comment]
Closing in lieu of https://community.omnisci.com/t/start-mapd-error-c5208/1834
