### ISSUE TITLE
Build error /bin/sh: BISONPP_EXECUTABLE-NOTFOUND: command not found

### ISSUE THREAD

**Issue by pickou** [omnisci/mapd-core#302]
When I compile the project, I ran into two issues below.
+ Build error /bin/sh: BISONPP_EXECUTABLE-NOTFOUND: command not found
+ nvcc fatal   : Value 'c++14' is not defined for option 'std'

My compiling environment is `Ubuntu 14.04 LTS`.

The mapD use `c++14` to build the project, and what is the cuda version(>8.0)?
I have found that the cuda-9.0 support c++14.

```
/bin/sh: BISONPP_EXECUTABLE-NOTFOUND: command not found
[  3%] Built target ScannerFiles
Parser/CMakeFiles/ParserFiles.dir/build.make:60: recipe for target 'Parser/Parser.cpp' failed
make[2]: *** [Parser/Parser.cpp] Error 127
[  4%] Built target linenoise
CMakeFiles/Makefile2:1143: recipe for target 'Parser/CMakeFiles/ParserFiles.dir/all' failed
make[1]: *** [Parser/CMakeFiles/ParserFiles.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Generating libProfileUtils.so
[  6%] Built target mapd_java_components
[  7%] Built target CudaMgr
nvcc fatal   : Value 'c++14' is not defined for option 'std'
[  8%] Generating bin/mapd_web_server
Tests/CMakeFiles/ProfileUtils.dir/build.make:61: recipe for target 'Tests/libProfileUtils.so' failed
make[2]: *** [Tests/libProfileUtils.so] Error 1
CMakeFiles/Makefile2:2496: recipe for target 'Tests/CMakeFiles/ProfileUtils.dir/all' failed
make[1]: *** [Tests/CMakeFiles/ProfileUtils.dir/all] Error 2
````

**Comment by pickou** [comment]
I have solved the first issue. Cause I haven't installed `bison++`. The camke got no error, so I missed it.
Use `sudo apt install bision++`, then the first issue solved.

**Comment by randyzwitch** [comment]
Hi @pickou - 

It's always tough to debug build issues like this; one thing I can say is that with Ubuntu 14.04LTS, the apt installer is going to have packages where the versions are too old to meet all of our requirements. What this means is that you'll need to do a lot of manual installation and configuration.

I'd highly recommend using our provided [Docker image](https://github.com/omnisci/mapd-core/tree/master/docker) or creating your own Docker image with a newer Ubuntu (our internal development team uses 18.04LTS). You can find all of the dependencies to install in our [scripts folder](https://github.com/omnisci/mapd-core/tree/master/scripts).

If you use our Docker container or one of the script files and find that things still don't compile, please let us know. While we do our best to keep all of these files up to date, occasionally we miss something.

Best,
Randy

**Comment by cdessanti** [comment]
Hi @pickou ,

to compile the latest version of mapd-core, you need gcc6 and  cuda >8.0 because of stc++ 14

**Comment by pickou** [comment]
Thank you for your response. @randyzwitch @cdessanti , I have solved the issue with `cuda10.0`, and after that I met other issues, then I soved it by `compiling the llvm from sourse`. 

I met the issue bellow,
```
/usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<const TDBObjectType::type>) (const TDBObjectType::type&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
```
I followed someone's step to `update the g++ version to 7.0`, then it worked! 
Thank you guys.

**Comment by randyzwitch** [comment]
Glad it worked out! Please feel free to stop by https://community.omnisci.com, we'd love to hear about your successes with OmniSci :)
