### ISSUE TITLE
mapd-ce-cpu image tag 4.4.0

### ISSUE THREAD

**Issue by xmnlab** [omnisci/mapd-core#304]
hey everyone! 

it seems there is no image tag 4.4.0 on https://hub.docker.com/r/mapd/mapd-ce-cpu/tags
I suppose that `latest` is for tag 4.4.0 but it is possible to have a specific tag for 4.4.0?
this tag would be very helpful to pinned this version inside ibis CI scripts (https://github.com/ibis-project/ibis/pull/1681).

thanks!

**Comment by randyzwitch** [comment]
4.4.1 is now on Docker.

**Comment by xmnlab** [comment]
thanks so much!
