### ISSUE TITLE
Maps view is blank in online demo instances

### ISSUE THREAD

**Issue by archenroot** [omnisci/mapd-core#307]
I checked one demo site:
https://www.omnisci.com/demos/taxis/#/dashboard/10?_k=ejpmlm

And second with 11bilion of data and aggregated views display just fine, but map view is blank, no map visible.

**Comment by randyzwitch** [comment]
Looks like it was just a temporary glitch, the demos are working now from my computer

![screenshot from 2019-01-03 08-21-17](https://user-images.githubusercontent.com/2762787/50639777-a6098780-0f30-11e9-95a2-4ebe470b8cec.png)
![screenshot from 2019-01-03 08-20-30](https://user-images.githubusercontent.com/2762787/50639778-a6098780-0f30-11e9-8e66-662e9dc571b4.png)

**Comment by archenroot** [comment]
Strange, it is still blank and in console I see
```
api.mapbox.com/style…By-SmxIONNGignoxw:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
/demos/ships/#/dashboard/8?_k=jjoj6v:1 Access to XMLHttpRequest at 'https://api.mapbox.com/styles/v1/mapbox/light-v8?access_token=pk.eyJ1IjoibWFwZCIsImEiOiJjajZmOGYzNG0wZTZwMnltbDhoaG50YzFiIn0.IzTw2By-SmxIONNGignoxw' from origin 'https://www.omnisci.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
vendor.7b222f6….js:1 
ProgressEvent
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
defaultPrevented: false
eventPhase: 0
isTrusted: true
lengthComputable: false
loaded: 0
path: []
returnValue: true
srcElement: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
target: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
timeStamp: 12005.999999999403
total: 0
type: "error"
__proto__: ProgressEvent
```
I use Chromium with config:
`Installed versions:  70.0.3538.67-r1^d(07:12:21 PM 10/22/2018)(cups custom-cflags hangouts jumbo-build kerberos pic proprietary-codecs pulseaudio suid -component-build -gnome-keyring -neon -selinux -system-ffmpeg -system-icu -system-libvpx -tcmalloc -widevine KERNEL="linux" L10N="am ar bg bn ca cs da de el en-GB es es-419 et fa fi fil fr gu he hi hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv sw ta te th tr uk vi zh-CN zh-TW")`

**Comment by archenroot** [comment]
Firefox and Opera also not working :-)
