### ISSUE TITLE
Select * from t limit 1; doesn't return anything...

### ISSUE THREAD

**Issue by archenroot** [omnisci/mapd-core#312]
So I have table with Taxi drives:
```
select count (*) from yellow_tripdata_2010_06 limit 100;
EXPR$0
1973666755
```
When I do group by limit I get some result:
```
select vendor_id from yellow_tripdata_2010_06 group by vendor_id limit 1;
vendor_idCMT
```

But when I do simply list some limited recordset (can be random, or ordered by default) I get nothing:
```
select vendor_id from yellow_tripdata_2010_06 limit 100;
vendor_id
Success: 0 rows in 10ms
```

I am not sure whether it is bug or feature? :-)

**Comment by cdessanti** [comment]
Hi,

which version are you using? I have a table with the same data as yours and I haven't any problem

with the vendor field as TEXT ENCODING DICT(8) the query runs flawlessly

100 rows returned.
Execution time: 252 ms, Total time: 253 ms

which datatype are you using?

**Comment by randyzwitch** [comment]
As @cdessanti mentions, simple select statements are supported.
