### ISSUE TITLE
Needed a single revision wehn build

### ISSUE THREAD

**Issue by seenyea** [omnisci/mapd-core#319]
user@user-System-Product-Name:~/Desktop/app/mapd-core-4.4.2/build$ cmake -DCMAKE_BUILD_TYPE=debug ..
-- Looking for bison++
fatal: Needed a single revision
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Desktop/app/mapd-core-4.4.2/build

**Comment by seenyea** [comment]
It looks following commands in CMakeLists.txt cause the issue:\
execute_process(
  COMMAND ${GIT_EXECUTABLE} rev-parse --short=10 HEAD
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE MAPD_GIT_HASH
  OUTPUT_STRIP_TRAILING_WHITESPACE
  )

I just downloaded the tarball from the release frame of mapd-core.

**Comment by randyzwitch** [comment]
Hi @seenyea - 

Do you still need help with this, or did downloading a tarball fix your issues? If you still need help, please let us know what environment you are trying to build for and CPU or GPU build.

**Comment by seenyea** [comment]
I have fixed it:
1. I re-download your master branch, then checkout your tags/v4.4.2. 
2. run "mapd-deps-ubuntu1604.sh" in the scripts folder.

**Comment by randyzwitch** [comment]
Great, glad you figured it out.
