### ISSUE TITLE
mapd-core persistence

### ISSUE THREAD

**Issue by ayanray089** [omnisci/mapd-core#320]
Hi,

Is mapd-core persistent? If so, what is the persistent technique?

Thanks!

**Comment by randyzwitch** [comment]
Hi @ayanray089 -

This question is more appropriate for https://community.omnisci.com, as the “issues” section here is for reporting bugs or discussion about developing new features via pull requests.

In terms of persisting data, yes, OmniSci stores the data on disk, loading it on request via query.

Best,
Randy
