### ISSUE TITLE
A bigint value is truncated to integer when asking for string in a jdbc resultset

### ISSUE THREAD

**Issue by cdessanti** [omnisci/mapd-core#330]
see this post on community forums

https://community.omnisci.com/communities/community-home/digestviewer/viewthread?GroupId=13&MID=4053&CommunityKey=d06df790-8ca4-4e54-91a0-244af0228ddc&tab=digestviewer&ReturnUrl=%2fforum

**Comment by randyzwitch** [comment]
Fixed by #331
