### ISSUE TITLE
Add links to prebuilt binaries and install docs

### ISSUE THREAD

**Issue by andrewseidl** [omnisci/mapd-core#342]
With the release of v4.5.0 we're now generating "official" binaries from the open source repo. Update the readme to link to these and the apt and yum repos.

**Comment by andrewseidl** [comment]
| Distro | Package type | CPU/GPU | Link | Docs |
| --- | --- | --- | --- | --- |
| CentOS | RPM | CPU | https://releases.omnisci.com/os/yum/stable/cpu | https://www.omnisci.com/docs/latest/4_centos7-yum-cpu-os-recipe.html |
| CentOS | RPM | GPU | https://releases.omnisci.com/os/yum/stable/cuda | https://www.omnisci.com/docs/latest/4_centos7-yum-gpu-os-recipe.html |
| Ubuntu | DEB | CPU | deb https://releases.omnisci.com/os/apt/ stable cpu | https://www.omnisci.com/docs/latest/4_ubuntu-apt-cpu-os-recipe.html |
| Ubuntu | DEB | GPU | deb https://releases.omnisci.com/os/apt/ stable cuda | https://www.omnisci.com/docs/latest/4_ubuntu-apt-gpu-os-recipe.html |
| * | tarball | CPU | https://releases.omnisci.com/os/tar/omnisci-os-latest-Linux-x86_64-cpu.tar.gz |  |
| * | tarball | GPU | https://releases.omnisci.com/os/tar/omnisci-os-latest-Linux-x86_64-cuda.tar.gz |  |

**Comment by jrajav** [comment]
It would be good to move the Downloads section right to the top of the Readme too (even if it's just a big bold subsection link), as the main call-to-action for OSS visitors. It's pretty buried and nonobvious, right now, which could be a barrier.

**Comment by randyzwitch** [comment]
Agreed @jrajav. This also highlights that we're getting even closer towards https://github.com/omnisci/mapd-core/pull/263 being a good idea.
