### ISSUE TITLE
"core-os-cpu" docker image is not working

### ISSUE THREAD

**Issue by QuadTriangle** [omnisci/mapd-core#346]
I have tried both "mapd/core-os-cpu" and "omnisci/core-os-cpu".  But Frontend is not accessible at
"localhost:6273"

```
docker run --network host mapd/core-os-cpu
Backend TCP:  localhost:6274
Backend HTTP: localhost:6278
Frontend Web: localhost:6273
Calcite TCP: localhost:6279
WARN: config file does not exist, ignoring: --config /omnisci-storage/omnisci.conf
E0501 07:38:35.583144   374 MapDHandler.cpp:185] This build isn't CUDA enabled, will run on CPU
```

"mapd/mapd-ce-cpu" is working fine.

**Comment by dwayneberry** [comment]
@QuadTriangle
Thanks for looking at Omnisci
Please review features of OmniSci post version 4.5 here https://www.omnisci.com/platform/downloads/
Community edition is no longer available, to use Immerse you can get access via an enterprise trial or cloud.
regards

**Comment by QuadTriangle** [comment]
@dwayneberry Can I still use v4.4.2 Immerse?
I tried to build v4.4.2. Same problem.

**Comment by cdessanti** [comment]
Yes you can use the old version of Immerse, but the new core builds come with backend rendering disabled, so you have a limited set of viz; the only geospatial one is the old client side choropleth map

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by cdessanti** [comment]
I forgot to point out, that using an older version of immerse with a newer version of the core database could lead to unpredictable behavior of the software itself because of the misalignment of APIs.

To use a full docker image (core+immerse) you should change the immerse ports on docker config to 9092

**Comment by QuadTriangle** [comment]
@cdessanti thanks.
